// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Sythos (https://www.sythos.net)
// Author: Sythos (https://www.sythos.net)

const DEFAULT_TIMEOUT_MS = 5_000;
const MIN_TIMEOUT_MS = 1;
const MAX_TIMEOUT_MS = 120_000;
const USERNAME_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/u;
const MODULE_PATTERN = /^[A-Za-z][A-Za-z0-9]{0,63}$/u;
const FUNCTION_PATTERN = /^[A-Za-z][A-Za-z0-9_]{0,127}$/u;

interface CodedError extends Error {
  readonly code: string;
}

/**
 * The seam every consumer of the cPanel API talks to, so a test can inject a
 * fully deterministic fake instead of exercising `createCpanelApiClient()`'s
 * real HTTP behavior. `callUapi` mirrors the shape of a cPanel UAPI call:
 * `https://<host>:2083/execute/<module>/<function>?<params>`.
 */
export interface CpanelApiClientLike {
  callUapi(module: string, function_: string, params?: Record<string, string>): Promise<unknown>;
}

export interface CpanelApiClientOptions {
  /** e.g. `https://127.0.0.1:2083`. Must be HTTPS, no embedded credentials. */
  readonly baseUrl: string;
  readonly username: string;
  /** Never logged and never interpolated into an error message. */
  readonly apiToken: string;
  readonly timeoutMs?: number;
  /** Injectable for tests; defaults to Node's global `fetch`. */
  readonly fetchImpl?: typeof fetch;
}

function cpanelApiError(message: string, code = 'CPANEL_API_ERROR'): CodedError {
  const error = new Error(`cPanel API client error: ${message}`) as CodedError;
  Object.defineProperty(error, 'code', { value: code, enumerable: true });
  return error;
}

function readBaseUrl(value: unknown): URL {
  if (typeof value !== 'string' || value.length === 0) {
    throw cpanelApiError('baseUrl is required', 'CONFIGURATION');
  }
  let parsed: URL;
  try {
    parsed = new URL(value);
  } catch {
    throw cpanelApiError('baseUrl is not a valid URL', 'CONFIGURATION');
  }
  if (parsed.protocol !== 'https:' || parsed.username.length > 0 || parsed.password.length > 0 || parsed.search.length > 0 || parsed.hash.length > 0) {
    throw cpanelApiError('baseUrl must be HTTPS without embedded credentials, query, or fragment', 'CONFIGURATION');
  }
  return parsed;
}

function readUsername(value: unknown): string {
  if (typeof value !== 'string' || !USERNAME_PATTERN.test(value)) {
    throw cpanelApiError('username is invalid', 'CONFIGURATION');
  }
  return value;
}

function readApiToken(value: unknown): string {
  // Deliberately no character-set check beyond "non-empty string": the
  // token is opaque, generated by cPanel, and must never appear verbatim in
  // any error message this module raises.
  if (typeof value !== 'string' || value.length === 0) {
    throw cpanelApiError('apiToken is required', 'CONFIGURATION');
  }
  return value;
}

function readTimeoutMs(value: unknown): number {
  if (value === undefined) return DEFAULT_TIMEOUT_MS;
  if (!Number.isSafeInteger(value) || (value as number) < MIN_TIMEOUT_MS || (value as number) > MAX_TIMEOUT_MS) {
    throw cpanelApiError(`timeoutMs must be an integer between ${MIN_TIMEOUT_MS} and ${MAX_TIMEOUT_MS}`, 'CONFIGURATION');
  }
  return value as number;
}

function isAbortError(error: unknown): boolean {
  return error !== null && typeof error === 'object' && (error as { name?: unknown }).name === 'AbortError';
}

/**
 * A thin, injectable HTTP client for cPanel's per-account UAPI
 * (`/execute/<module>/<function>`), authenticated with a cPanel API token
 * (`Authorization: cpanel <user>:<token>`). Deliberately does not assume
 * anything about individual UAPI response bodies beyond "valid JSON" —
 * callers (e.g. `cpanel-identity-client.ts`) interpret `data`/`errors`
 * themselves, since the exact shape of each UAPI call has not been verified
 * against a live cPanel host.
 */
export function createCpanelApiClient({
  baseUrl,
  username,
  apiToken,
  timeoutMs,
  fetchImpl = fetch,
}: CpanelApiClientOptions): CpanelApiClientLike {
  const origin = readBaseUrl(baseUrl);
  const canonicalUsername = readUsername(username);
  const canonicalApiToken = readApiToken(apiToken);
  const canonicalTimeoutMs = readTimeoutMs(timeoutMs);
  const authorizationHeader = `cpanel ${canonicalUsername}:${canonicalApiToken}`;

  async function callUapi(module: string, function_: string, params: Record<string, string> = {}): Promise<unknown> {
    if (typeof module !== 'string' || !MODULE_PATTERN.test(module)) {
      throw cpanelApiError('module is invalid', 'INVALID_INPUT');
    }
    if (typeof function_ !== 'string' || !FUNCTION_PATTERN.test(function_)) {
      throw cpanelApiError('function is invalid', 'INVALID_INPUT');
    }

    const url = new URL(`/execute/${module}/${function_}`, origin);
    for (const [key, value] of Object.entries(params)) {
      url.searchParams.set(key, value);
    }

    const controller = new AbortController();
    const timeoutHandle = setTimeout(() => controller.abort(), canonicalTimeoutMs);
    let response: Response;
    try {
      response = await fetchImpl(url, {
        method: 'GET',
        headers: { Authorization: authorizationHeader },
        signal: controller.signal,
      });
    } catch (error) {
      if (isAbortError(error)) {
        throw cpanelApiError(`UAPI ${module}::${function_} timed out after ${canonicalTimeoutMs}ms`, 'TIMEOUT');
      }
      throw cpanelApiError(`UAPI ${module}::${function_} request failed`, 'NETWORK_ERROR');
    } finally {
      clearTimeout(timeoutHandle);
    }

    if (!response.ok) {
      throw cpanelApiError(`UAPI ${module}::${function_} returned HTTP ${response.status}`, 'HTTP_ERROR');
    }

    let text: string;
    try {
      text = await response.text();
    } catch {
      throw cpanelApiError(`could not read the response body for UAPI ${module}::${function_}`, 'INVALID_RESPONSE');
    }

    try {
      return JSON.parse(text) as unknown;
    } catch {
      throw cpanelApiError(`response for UAPI ${module}::${function_} was not valid JSON`, 'INVALID_RESPONSE');
    }
  }

  return Object.freeze({ callUapi });
}
