// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Sythos (https://www.sythos.net)
// Author: Sythos (https://www.sythos.net)

import { randomUUID } from 'node:crypto';

/** Metadata-only trash retention contract. Content remains in adapter stores. */
export const RETENTION_SCHEMA_VERSION = 1 as const;
export const DEFAULT_TRASH_RETENTION_DAYS = 28;
export const DEFAULT_PURGE_BATCH_SIZE = 100;
export const DEFAULT_LOCK_LEASE_MS = 30_000;
export const RETENTION_ITEM_STATES = Object.freeze({ TRASHED: 'trashed', RESTORED: 'restored', PURGED: 'purged' } as const);
export const RETENTION_METRIC_NAMES = Object.freeze({
  ITEMS_TRASHED: 'gulogulo_retention_items_trashed_total', ITEMS_RESTORED: 'gulogulo_retention_items_restored_total', ITEMS_HELD: 'gulogulo_retention_items_held_total', ITEMS_LOCKED: 'gulogulo_retention_items_locked_total', PURGE_BATCHES: 'gulogulo_retention_purge_batches_total', PURGE_CANDIDATES: 'gulogulo_retention_purge_candidates_total', ITEMS_PURGED: 'gulogulo_retention_items_purged_total', ITEMS_SKIPPED: 'gulogulo_retention_items_skipped_total', PURGE_FAILURES: 'gulogulo_retention_purge_failures_total', HOLDS_ADDED: 'gulogulo_retention_holds_added_total', HOLDS_RELEASED: 'gulogulo_retention_holds_released_total',
} as const);

export type RetentionItemState = typeof RETENTION_ITEM_STATES[keyof typeof RETENTION_ITEM_STATES];
export interface RetentionScope { readonly tenantId: string; readonly userId: string; readonly itemId: string; }
export interface RetentionItem extends RetentionScope {
  readonly schemaVersion: typeof RETENTION_SCHEMA_VERSION; readonly resourceType: string; readonly generation: number; readonly state: RetentionItemState;
  readonly deletedAt: string; readonly retentionUntil: string | null; readonly restoredAt: string | null; readonly purgedAt: string | null;
  readonly holdIds: readonly string[]; readonly lock: Readonly<{ owner: string; acquiredAt: string; leaseExpiresAt: string }> | null;
}
export interface RetentionAuditEvent extends RetentionScope { readonly schemaVersion: typeof RETENTION_SCHEMA_VERSION; readonly event: string; readonly occurredAt: string; readonly actorId: string; readonly actorRole: string; readonly operationId?: string; readonly metadata: Readonly<Record<string, unknown>>; }
export interface RetentionItemOperation { readonly schemaVersion: typeof RETENTION_SCHEMA_VERSION; readonly operation: string; readonly item: RetentionItem; readonly audit?: RetentionAuditEvent; readonly idempotencyKey?: string; readonly holdId?: string; readonly lockId?: string; readonly idempotent?: boolean; }
export interface PurgeBatchResult { readonly schemaVersion: typeof RETENTION_SCHEMA_VERSION; readonly operation: 'purge_batch'; readonly operationId: string; readonly workerId: string; readonly startedAt: string; readonly completedAt: string; readonly batchSize: number; readonly scanned: number; readonly purged: number; readonly skipped: number; readonly failed: number; readonly remaining: number; readonly items: readonly RetentionItem[]; readonly skippedItems: readonly Readonly<{ itemId: string; reason: string }>[]; readonly failures: readonly Readonly<{ itemId: string; code: string }>[]; readonly auditEvents: readonly RetentionAuditEvent[]; readonly metrics: Readonly<Record<string, number>>; }

type UnknownRecord = Record<string, unknown>;
type DateInput = Date | string | number;
type Actor = { readonly actorId: string; readonly role: string };
type Hold = { readonly holdId: string; readonly reasonCode: string; readonly createdAt: string; readonly expiresAt: string | null };
type Lock = { readonly lockId: string; readonly owner: string; readonly acquiredAt: string; readonly leaseExpiresAt: string };
type RecordItem = { tenantId: string; userId: string; itemId: string; resourceType: string; generation: number; state: RetentionItemState; deletedAt: string; retentionUntil: string | null; restoredAt: string | null; purgedAt: string | null; holds: Map<string, Hold>; lock: Lock | null };

const DAY_MS = 86_400_000;
const ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,127}$/u;
const OPERATION_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/u;
const RESOURCE_PATTERN = /^[a-z][a-z0-9_-]{0,31}$/u;
const ROLE_PATTERN = /^[a-z][a-z0-9_-]{0,31}$/u;
const DEFAULT_RESOURCE_TYPES = new Set(['mail', 'calendar', 'contacts', 'preferences', 'backup']);

export function retentionError(message: string, code = 'RETENTION_ERROR'): Error & { code: string } { const error = new Error(`Retention error: ${message}`) as Error & { code: string }; error.code = code; return error; }
function isObject(value: unknown): value is UnknownRecord { return value !== null && typeof value === 'object' && !Array.isArray(value); }
function object(value: unknown, field: string): UnknownRecord { if (!isObject(value)) throw retentionError(`${field} must be an object`, 'INVALID_INPUT'); return value; }
export function assertId(value: unknown, field: string): string { if (typeof value !== 'string' || !ID_PATTERN.test(value)) throw retentionError(`${field} is invalid`, 'INVALID_IDENTITY'); return value; }
export function assertOperationId(value: unknown, field = 'operationId'): string { if (typeof value !== 'string' || !OPERATION_PATTERN.test(value)) throw retentionError(`${field} is invalid`, 'INVALID_OPERATION_ID'); return value; }
function date(value: unknown, field: string, fallback?: DateInput): Date { const selected = value === undefined ? fallback : value; const parsed = selected instanceof Date ? new Date(selected.getTime()) : new Date(selected as string | number); if (Number.isNaN(parsed.getTime())) throw retentionError(`${field} is invalid`, 'INVALID_TIMESTAMP'); return parsed; }
function iso(value: unknown, field: string, fallback?: DateInput): string { return date(value, field, fallback).toISOString(); }
function retentionDays(value: unknown): number { if (!Number.isInteger(value) || (value as number) < 1 || (value as number) > 3650) throw retentionError('retentionDays must be an integer between 1 and 3650', 'INVALID_RETENTION_POLICY'); return value as number; }
function batchSize(value: unknown, max: number): number { if (!Number.isInteger(value) || (value as number) < 1 || (value as number) > max) throw retentionError(`limit must be an integer between 1 and ${max}`, 'INVALID_BATCH_SIZE'); return value as number; }
function freeze<T>(value: T): Readonly<T> { if (Array.isArray(value)) return Object.freeze(value.map(freeze)) as unknown as Readonly<T>; if (isObject(value)) { const copy: UnknownRecord = {}; for (const [key, item] of Object.entries(value)) copy[key] = freeze(item); return Object.freeze(copy) as Readonly<T>; } return value; }
function actor(value: unknown, fallback?: string): Actor { if (value === undefined) return Object.freeze({ actorId: fallback ?? 'retention-worker', role: fallback ? 'user' : 'system' }); const input = object(value, 'actor'); const role = input.role ?? 'user'; if (typeof role !== 'string' || !ROLE_PATTERN.test(role)) throw retentionError('actor.role is invalid', 'INVALID_ROLE'); return Object.freeze({ actorId: assertId(input.actorId, 'actor.actorId'), role }); }
function scope(value: unknown): RetentionScope { const input = object(value, 'scope'); return { tenantId: assertId(input.tenantId, 'scope.tenantId'), userId: assertId(input.userId, 'scope.userId'), itemId: assertId(input.itemId, 'scope.itemId') }; }
function key(value: RetentionScope): string { return `${value.tenantId}\u0000${value.userId}\u0000${value.itemId}`; }
function activeHolds(item: RecordItem, now: Date): Hold[] { return [...item.holds.values()].filter((hold) => hold.expiresAt === null || new Date(hold.expiresAt).getTime() > now.getTime()); }
function locked(item: RecordItem, now: Date): boolean { return item.lock !== null && new Date(item.lock.leaseExpiresAt).getTime() > now.getTime(); }
function publicItem(item: RecordItem): RetentionItem { return freeze({ schemaVersion: RETENTION_SCHEMA_VERSION, tenantId: item.tenantId, userId: item.userId, itemId: item.itemId, resourceType: item.resourceType, generation: item.generation, state: item.state, deletedAt: item.deletedAt, retentionUntil: item.retentionUntil, restoredAt: item.restoredAt, purgedAt: item.purgedAt, holdIds: [...item.holds.keys()], lock: item.lock ? { owner: item.lock.owner, acquiredAt: item.lock.acquiredAt, leaseExpiresAt: item.lock.leaseExpiresAt } : null }); }
function audit(input: { event: string; item: RetentionScope; actor: Actor; occurredAt: unknown; operationId?: string; metadata?: UnknownRecord }): RetentionAuditEvent { return freeze({ schemaVersion: RETENTION_SCHEMA_VERSION, event: input.event, occurredAt: iso(input.occurredAt, 'occurredAt'), tenantId: input.item.tenantId, userId: input.item.userId, itemId: input.item.itemId, actorId: input.actor.actorId, actorRole: input.actor.role, ...(input.operationId ? { operationId: input.operationId } : {}), metadata: input.metadata ?? {} }); }
function resource(value: unknown): string { if (typeof value !== 'string' || !RESOURCE_PATTERN.test(value)) throw retentionError('resourceType is invalid', 'INVALID_RESOURCE_TYPE'); return value; }

export interface RetentionStore {
  readonly retentionDays: number; readonly maxBatchSize: number;
  markDeleted(input?: UnknownRecord): RetentionItemOperation; restoreItem(input?: UnknownRecord): RetentionItemOperation; addHold(input?: UnknownRecord): RetentionItemOperation; releaseHold(input?: UnknownRecord): RetentionItemOperation; acquireLock(input?: UnknownRecord): RetentionItemOperation; releaseLock(input?: UnknownRecord): RetentionItemOperation; listCandidates(input?: UnknownRecord): readonly RetentionItem[]; runPurgeBatch(input?: UnknownRecord): PurgeBatchResult; getItem(input: RetentionScope): RetentionItem; getAuditEvents(input?: UnknownRecord): readonly RetentionAuditEvent[]; getMetrics(): Readonly<Record<string, number>>; exportState(): Readonly<{ schemaVersion: typeof RETENTION_SCHEMA_VERSION; retentionDays: number; items: readonly RetentionItem[]; metrics: Readonly<Record<string, number>> }>;
}
export function createRetentionStore({ now = () => new Date(), retentionDays: configuredDays = DEFAULT_TRASH_RETENTION_DAYS, maxBatchSize = DEFAULT_PURGE_BATCH_SIZE, resourceTypes = DEFAULT_RESOURCE_TYPES, purgeItem }: { now?: () => DateInput; retentionDays?: number; maxBatchSize?: number; resourceTypes?: Iterable<string>; purgeItem?: (item: RetentionItem) => unknown } = {}): RetentionStore {
  if (typeof now !== 'function') throw retentionError('now must be a function', 'INVALID_CLOCK'); const policyDays = retentionDays(configuredDays); if (!Number.isInteger(maxBatchSize) || maxBatchSize < 1 || maxBatchSize > 10_000) throw retentionError('maxBatchSize must be between 1 and 10000', 'INVALID_BATCH_SIZE'); if (purgeItem !== undefined && typeof purgeItem !== 'function') throw retentionError('purgeItem must be a function when provided', 'INVALID_PURGE_ADAPTER');
  const allowed = new Set(resourceTypes); for (const type of allowed) resource(type); const records = new Map<string, RecordItem>(); const results = new Map<string, RetentionItemOperation | PurgeBatchResult>(); const events: RetentionAuditEvent[] = []; const metrics: Record<string, number> = Object.fromEntries(Object.values(RETENTION_METRIC_NAMES).map((name) => [name, 0]));
  const current = (): Date => date(now(), 'clock'); const increment = (name: string, amount = 1): void => { metrics[name] = (metrics[name] ?? 0) + amount; }; const requireItem = (input: unknown): { itemScope: RetentionScope; item: RecordItem } => { const itemScope = scope(input); const item = records.get(key(itemScope)); if (!item) throw retentionError('item does not exist', 'ITEM_NOT_FOUND'); return { itemScope, item }; };
  const itemOperation = (operation: string, item: RecordItem, value: UnknownRecord = {}): RetentionItemOperation => freeze({ schemaVersion: RETENTION_SCHEMA_VERSION, operation, item: publicItem(item), ...value });
  const listCandidates = (input: UnknownRecord = {}): readonly RetentionItem[] => { const asOf = date(input.asOf, 'asOf', current()); const limit = batchSize(input.limit ?? maxBatchSize, maxBatchSize); const tenant = input.tenantId === undefined ? undefined : assertId(input.tenantId, 'tenantId'); const user = input.userId === undefined ? undefined : assertId(input.userId, 'userId'); if (user && !tenant) throw retentionError('tenantId is required with userId', 'INVALID_SCOPE'); return [...records.values()].filter((item) => item.state === RETENTION_ITEM_STATES.TRASHED && (tenant === undefined || item.tenantId === tenant) && (user === undefined || item.userId === user) && item.retentionUntil !== null && new Date(item.retentionUntil).getTime() <= asOf.getTime() && activeHolds(item, asOf).length === 0 && !locked(item, asOf)).sort((left, right) => (left.retentionUntil ?? '').localeCompare(right.retentionUntil ?? '') || key(left).localeCompare(key(right))).slice(0, limit).map(publicItem); };
  const markDeleted = (input: UnknownRecord = {}): RetentionItemOperation => { const itemScope = scope(input); const type = resource(input.resourceType); if (!allowed.has(type)) throw retentionError(`resourceType ${type} is not enabled`, 'RESOURCE_TYPE_DISABLED'); const id = assertOperationId(input.idempotencyKey ?? randomUUID(), 'idempotencyKey'); const resultKey = `delete\u0000${key(itemScope)}\u0000${id}`; const oldResult = results.get(resultKey); if (oldResult) return oldResult as RetentionItemOperation; const deletedAt = date(input.deletedAt, 'deletedAt', current()); const prior = records.get(key(itemScope)); const item: RecordItem = { ...itemScope, resourceType: type, generation: prior ? prior.generation + 1 : 1, state: RETENTION_ITEM_STATES.TRASHED, deletedAt: deletedAt.toISOString(), retentionUntil: new Date(deletedAt.getTime() + policyDays * DAY_MS).toISOString(), restoredAt: null, purgedAt: null, holds: prior?.holds ?? new Map(), lock: null }; records.set(key(itemScope), item); increment(RETENTION_METRIC_NAMES.ITEMS_TRASHED); const entry = audit({ event: 'retention.item_trashed', item: itemScope, actor: actor(input.actor, itemScope.userId), occurredAt: deletedAt, operationId: id, metadata: { resourceType: type, generation: item.generation, retentionUntil: item.retentionUntil } }); events.push(entry); const output = itemOperation('item_trashed', item, { idempotencyKey: id, audit: entry }); results.set(resultKey, output); return output; };
  const restoreItem = (input: UnknownRecord = {}): RetentionItemOperation => { const itemScope = scope(input); const id = assertOperationId(input.idempotencyKey ?? randomUUID(), 'idempotencyKey'); const resultKey = `restore\u0000${key(itemScope)}\u0000${id}`; const oldResult = results.get(resultKey); if (oldResult) return oldResult as RetentionItemOperation; const { item } = requireItem(itemScope); if (item.state === RETENTION_ITEM_STATES.PURGED) throw retentionError('purged content cannot be restored by this contract', 'ITEM_ALREADY_PURGED'); const restoredAt = date(input.restoredAt, 'restoredAt', current()); item.state = RETENTION_ITEM_STATES.RESTORED; item.restoredAt = restoredAt.toISOString(); item.retentionUntil = null; item.lock = null; increment(RETENTION_METRIC_NAMES.ITEMS_RESTORED); const entry = audit({ event: 'retention.item_restored', item: itemScope, actor: actor(input.actor, itemScope.userId), occurredAt: restoredAt, operationId: id, metadata: { generation: item.generation } }); events.push(entry); const output = itemOperation('item_restored', item, { idempotencyKey: id, audit: entry }); results.set(resultKey, output); return output; };
  const addHold = (input: UnknownRecord = {}): RetentionItemOperation => { const itemScope = scope(input); const holdId = assertOperationId(input.holdId, 'holdId'); if (typeof input.reasonCode !== 'string' || input.reasonCode.length < 1 || input.reasonCode.length > 256 || /[\r\n]/u.test(input.reasonCode)) throw retentionError('reasonCode must contain 1-256 single-line characters', 'INVALID_HOLD_REASON'); const { item } = requireItem(itemScope); const expiresAt = input.expiresAt === null || input.expiresAt === undefined ? null : iso(input.expiresAt, 'expiresAt'); if (expiresAt && new Date(expiresAt).getTime() <= current().getTime()) throw retentionError('expiresAt must be in the future', 'INVALID_HOLD_EXPIRY'); if (item.holds.has(holdId)) return itemOperation('hold_added', item, { holdId, idempotent: true }); item.holds.set(holdId, { holdId, reasonCode: input.reasonCode, createdAt: iso(input.occurredAt, 'occurredAt', current()), expiresAt }); increment(RETENTION_METRIC_NAMES.ITEMS_HELD); increment(RETENTION_METRIC_NAMES.HOLDS_ADDED); const entry = audit({ event: 'retention.hold_added', item: itemScope, actor: actor(input.actor, itemScope.userId), occurredAt: input.occurredAt ?? current(), metadata: { holdId, reasonCode: input.reasonCode, expiresAt } }); events.push(entry); return itemOperation('hold_added', item, { holdId, audit: entry }); };
  const releaseHold = (input: UnknownRecord = {}): RetentionItemOperation => { const itemScope = scope(input); const holdId = assertOperationId(input.holdId, 'holdId'); const { item } = requireItem(itemScope); if (!item.holds.has(holdId)) return itemOperation('hold_released', item, { holdId, idempotent: true }); item.holds.delete(holdId); increment(RETENTION_METRIC_NAMES.HOLDS_RELEASED); const entry = audit({ event: 'retention.hold_released', item: itemScope, actor: actor(input.actor, itemScope.userId), occurredAt: input.occurredAt ?? current(), metadata: { holdId } }); events.push(entry); return itemOperation('hold_released', item, { holdId, audit: entry }); };
  const acquireLock = (input: UnknownRecord = {}): RetentionItemOperation => { const itemScope = scope(input); const lockId = assertOperationId(input.lockId ?? randomUUID(), 'lockId'); const owner = assertId(input.owner, 'owner'); const leaseMs = input.leaseMs ?? DEFAULT_LOCK_LEASE_MS; if (!Number.isInteger(leaseMs) || (leaseMs as number) < 1000 || (leaseMs as number) > DAY_MS) throw retentionError('leaseMs must be between 1000 and 86400000 milliseconds', 'INVALID_LOCK_LEASE'); const acquiredAt = date(input.acquiredAt, 'acquiredAt', current()); const { item } = requireItem(itemScope); if (item.lock && locked(item, acquiredAt) && item.lock.owner !== owner) throw retentionError('item is locked by another worker', 'ITEM_LOCKED'); item.lock = { lockId, owner, acquiredAt: acquiredAt.toISOString(), leaseExpiresAt: new Date(acquiredAt.getTime() + (leaseMs as number)).toISOString() }; increment(RETENTION_METRIC_NAMES.ITEMS_LOCKED); return itemOperation('item_locked', item, { lockId }); };
  const releaseLock = (input: UnknownRecord = {}): RetentionItemOperation => { const itemScope = scope(input); const lockId = assertOperationId(input.lockId, 'lockId'); const owner = assertId(input.owner, 'owner'); const { item } = requireItem(itemScope); if (!item.lock || item.lock.lockId !== lockId || item.lock.owner !== owner) throw retentionError('lock does not belong to the owner', 'LOCK_NOT_OWNED'); item.lock = null; return itemOperation('item_unlocked', item); };
  const runPurgeBatch = (input: UnknownRecord = {}): PurgeBatchResult => { const workerId = assertId(input.workerId, 'workerId'); const operationId = assertOperationId(input.operationId ?? randomUUID()); const tenant = input.tenantId === undefined ? '*' : assertId(input.tenantId, 'tenantId'); const user = input.userId === undefined ? '*' : assertId(input.userId, 'userId'); if (user !== '*' && tenant === '*') throw retentionError('tenantId is required with userId', 'INVALID_SCOPE'); const limit = batchSize(input.limit ?? maxBatchSize, maxBatchSize); const resultKey = `purge\u0000${workerId}\u0000${tenant}\u0000${user}\u0000${operationId}`; const prior = results.get(resultKey); if (prior) return prior as PurgeBatchResult; const startedAt = date(input.startedAt, 'startedAt', current()); const callback = input.purgeItem === undefined ? purgeItem : input.purgeItem; if (callback !== undefined && typeof callback !== 'function') throw retentionError('purgeItem must be a function when provided', 'INVALID_PURGE_ADAPTER'); const candidates = listCandidates({ tenantId: tenant === '*' ? undefined : tenant, userId: user === '*' ? undefined : user, asOf: startedAt, limit }); increment(RETENTION_METRIC_NAMES.PURGE_BATCHES); increment(RETENTION_METRIC_NAMES.PURGE_CANDIDATES, candidates.length); const items: RetentionItem[] = []; const skippedItems: { itemId: string; reason: string }[] = []; const failures: { itemId: string; code: string }[] = []; const batchEvents: RetentionAuditEvent[] = []; const worker: Actor = { actorId: workerId, role: 'system' };
    for (const candidate of candidates) { const item = records.get(key(candidate)); if (!item || item.state !== RETENTION_ITEM_STATES.TRASHED || item.retentionUntil === null || new Date(item.retentionUntil).getTime() > startedAt.getTime() || activeHolds(item, startedAt).length > 0 || locked(item, startedAt)) { skippedItems.push({ itemId: candidate.itemId, reason: 'state_changed' }); continue; } item.lock = { lockId: operationId, owner: workerId, acquiredAt: startedAt.toISOString(), leaseExpiresAt: new Date(startedAt.getTime() + DEFAULT_LOCK_LEASE_MS).toISOString() }; try { const adapterResult = callback ? (callback as (value: RetentionItem) => unknown)(publicItem(item)) : undefined; if (adapterResult === false) throw retentionError('purge adapter rejected the item', 'PURGE_REJECTED'); if (isObject(adapterResult) && typeof adapterResult.then === 'function') throw retentionError('purgeItem must be synchronous in this contract', 'ASYNC_PURGE_ADAPTER'); } catch (error) { const code = isObject(error) && typeof error.code === 'string' ? error.code : 'PURGE_ADAPTER_ERROR'; failures.push({ itemId: item.itemId, code }); increment(RETENTION_METRIC_NAMES.PURGE_FAILURES); const entry = audit({ event: 'retention.purge_failed', item, actor: worker, occurredAt: startedAt, operationId, metadata: { resourceType: item.resourceType, generation: item.generation, code } }); events.push(entry); batchEvents.push(entry); item.lock = null; skippedItems.push({ itemId: item.itemId, reason: 'purge_failed' }); continue; }
      if (item.state !== RETENTION_ITEM_STATES.TRASHED || item.retentionUntil === null || new Date(item.retentionUntil).getTime() > startedAt.getTime() || activeHolds(item, startedAt).length > 0) { item.lock = null; skippedItems.push({ itemId: item.itemId, reason: 'state_changed' }); continue; } item.state = RETENTION_ITEM_STATES.PURGED; item.purgedAt = startedAt.toISOString(); item.lock = null; increment(RETENTION_METRIC_NAMES.ITEMS_PURGED); const entry = audit({ event: 'retention.purge', item, actor: worker, occurredAt: startedAt, operationId, metadata: { resourceType: item.resourceType, generation: item.generation } }); events.push(entry); batchEvents.push(entry); items.push(publicItem(item)); }
    increment(RETENTION_METRIC_NAMES.ITEMS_SKIPPED, skippedItems.length); const completedAt = current(); const remaining = listCandidates({ tenantId: tenant === '*' ? undefined : tenant, userId: user === '*' ? undefined : user, asOf: completedAt, limit: maxBatchSize }).length; const output = freeze({ schemaVersion: RETENTION_SCHEMA_VERSION, operation: 'purge_batch' as const, operationId, workerId, startedAt: startedAt.toISOString(), completedAt: completedAt.toISOString(), batchSize: limit, scanned: candidates.length, purged: items.length, skipped: skippedItems.length, failed: failures.length, remaining, items, skippedItems, failures, auditEvents: batchEvents, metrics: { ...metrics } }) as PurgeBatchResult; results.set(resultKey, output); return output;
  };
  const getAuditEvents = (input: UnknownRecord = {}): readonly RetentionAuditEvent[] => { const tenant = input.tenantId === undefined ? undefined : assertId(input.tenantId, 'tenantId'); const user = input.userId === undefined ? undefined : assertId(input.userId, 'userId'); if (user && !tenant) throw retentionError('tenantId is required with userId', 'INVALID_SCOPE'); if (input.event !== undefined && (typeof input.event !== 'string' || !/^retention\.[a-z_]+$/u.test(input.event))) throw retentionError('event is invalid', 'INVALID_AUDIT_FILTER'); return freeze(events.filter((entry) => (tenant === undefined || entry.tenantId === tenant) && (user === undefined || entry.userId === user) && (input.event === undefined || entry.event === input.event))); };
  return Object.freeze({ retentionDays: policyDays, maxBatchSize, markDeleted, restoreItem, addHold, releaseHold, acquireLock, releaseLock, listCandidates, runPurgeBatch, getItem: (input: RetentionScope): RetentionItem => publicItem(requireItem(input).item), getAuditEvents, getMetrics: (): Readonly<Record<string, number>> => freeze({ ...metrics }) as Readonly<Record<string, number>>, exportState: () => freeze({ schemaVersion: RETENTION_SCHEMA_VERSION, retentionDays: policyDays, items: [...records.values()].map(publicItem), metrics: { ...metrics } }) as Readonly<{ schemaVersion: typeof RETENTION_SCHEMA_VERSION; retentionDays: number; items: readonly RetentionItem[]; metrics: Readonly<Record<string, number>> }> });
}
