// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Sythos (https://www.sythos.net)
// Author: Sythos (https://www.sythos.net)

const DEFAULT_TIMEOUT_MS = 5_000;
const MIN_TIMEOUT_MS = 1;
const MAX_TIMEOUT_MS = 120_000;
const METHOD_PATTERN = /^(GET|POST|PUT|PATCH|DELETE)$/u;
const PATH_PATTERN = /^\/api\/v2\/[A-Za-z0-9/_-]*$/u;

interface CodedError extends Error {
  readonly code: string;
}

/**
 * The seam every consumer of the Plesk API talks to, so a test can inject a
 * fully deterministic fake instead of exercising `createPleskApiClient()`'s
 * real HTTP behavior. `request` mirrors the shape of a Plesk REST call:
 * `https://<host>:8443/api/v2/<path>`, addressed by HTTP method + path
 * rather than cPanel's UAPI module/function pair.
 */
export interface PleskApiClientLike {
  request(method: string, path: string, body?: unknown): Promise<unknown>;
}

export interface PleskApiClientOptions {
  /** e.g. `https://127.0.0.1:8443`. Must be HTTPS, no embedded credentials. */
  readonly baseUrl: string;
  /** Never logged and never interpolated into an error message. */
  readonly apiKey: string;
  readonly timeoutMs?: number;
  /** Injectable for tests; defaults to Node's global `fetch`. */
  readonly fetchImpl?: typeof fetch;
}

function pleskApiError(message: string, code = 'PLESK_API_ERROR'): CodedError {
  const error = new Error(`Plesk API client error: ${message}`) as CodedError;
  Object.defineProperty(error, 'code', { value: code, enumerable: true });
  return error;
}

function readBaseUrl(value: unknown): URL {
  if (typeof value !== 'string' || value.length === 0) {
    throw pleskApiError('baseUrl is required', 'CONFIGURATION');
  }
  let parsed: URL;
  try {
    parsed = new URL(value);
  } catch {
    throw pleskApiError('baseUrl is not a valid URL', 'CONFIGURATION');
  }
  if (parsed.protocol !== 'https:' || parsed.username.length > 0 || parsed.password.length > 0 || parsed.search.length > 0 || parsed.hash.length > 0) {
    throw pleskApiError('baseUrl must be HTTPS without embedded credentials, query, or fragment', 'CONFIGURATION');
  }
  return parsed;
}

function readApiKey(value: unknown): string {
  // Deliberately no character-set check beyond "non-empty string": the key
  // is opaque, generated by Plesk, and must never appear verbatim in any
  // error message this module raises.
  if (typeof value !== 'string' || value.length === 0) {
    throw pleskApiError('apiKey is required', 'CONFIGURATION');
  }
  return value;
}

function readTimeoutMs(value: unknown): number {
  if (value === undefined) return DEFAULT_TIMEOUT_MS;
  if (!Number.isSafeInteger(value) || (value as number) < MIN_TIMEOUT_MS || (value as number) > MAX_TIMEOUT_MS) {
    throw pleskApiError(`timeoutMs must be an integer between ${MIN_TIMEOUT_MS} and ${MAX_TIMEOUT_MS}`, 'CONFIGURATION');
  }
  return value as number;
}

function isAbortError(error: unknown): boolean {
  return error !== null && typeof error === 'object' && (error as { name?: unknown }).name === 'AbortError';
}

/**
 * A thin, injectable HTTP client for Plesk's modern REST API
 * (`/api/v2/<path>`), authenticated with a Plesk API key
 * (`X-API-Key: <key>`). Deliberately does not assume anything about
 * individual endpoint response bodies beyond "valid JSON" — callers (e.g.
 * `plesk-identity-client.ts`) interpret the payload themselves, since the
 * exact shape of each REST endpoint has not been verified against a live
 * Plesk host.
 */
export function createPleskApiClient({
  baseUrl,
  apiKey,
  timeoutMs,
  fetchImpl = fetch,
}: PleskApiClientOptions): PleskApiClientLike {
  const origin = readBaseUrl(baseUrl);
  const canonicalApiKey = readApiKey(apiKey);
  const canonicalTimeoutMs = readTimeoutMs(timeoutMs);

  async function request(method: string, path: string, body?: unknown): Promise<unknown> {
    if (typeof method !== 'string' || !METHOD_PATTERN.test(method)) {
      throw pleskApiError('method is invalid', 'INVALID_INPUT');
    }
    if (typeof path !== 'string' || !PATH_PATTERN.test(path)) {
      throw pleskApiError('path is invalid', 'INVALID_INPUT');
    }

    const url = new URL(path, origin);
    const headers: Record<string, string> = { 'X-API-Key': canonicalApiKey };
    let requestBody: string | undefined;
    if (body !== undefined) {
      headers['Content-Type'] = 'application/json';
      try {
        requestBody = JSON.stringify(body);
      } catch {
        throw pleskApiError('request body could not be serialized to JSON', 'INVALID_INPUT');
      }
    }

    const controller = new AbortController();
    const timeoutHandle = setTimeout(() => controller.abort(), canonicalTimeoutMs);
    let response: Response;
    try {
      response = await fetchImpl(url, {
        method,
        headers,
        body: requestBody,
        signal: controller.signal,
      });
    } catch (error) {
      if (isAbortError(error)) {
        throw pleskApiError(`${method} ${path} timed out after ${canonicalTimeoutMs}ms`, 'TIMEOUT');
      }
      throw pleskApiError(`${method} ${path} request failed`, 'NETWORK_ERROR');
    } finally {
      clearTimeout(timeoutHandle);
    }

    if (!response.ok) {
      throw pleskApiError(`${method} ${path} returned HTTP ${response.status}`, 'HTTP_ERROR');
    }

    let text: string;
    try {
      text = await response.text();
    } catch {
      throw pleskApiError(`could not read the response body for ${method} ${path}`, 'INVALID_RESPONSE');
    }

    if (text.length === 0) return null;

    try {
      return JSON.parse(text) as unknown;
    } catch {
      throw pleskApiError(`response for ${method} ${path} was not valid JSON`, 'INVALID_RESPONSE');
    }
  }

  return Object.freeze({ request });
}
