// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Sythos (https://www.sythos.net)
// Author: Sythos (https://www.sythos.net)

import { createCipheriv, createDecipheriv, createHash, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';

export const BACKUP_SCHEMA_VERSION = 1 as const;
export const BACKUP_ENVELOPE_VERSION = 1 as const;
export const BACKUP_LINK_TTL_MAX_MS = 86_400_000;
export const BACKUP_RESOURCE_TYPES = Object.freeze(['mail', 'folders', 'ics', 'vcard', 'preferences'] as const);
export const BACKUP_PROVIDER_OPERATIONS = Object.freeze(['snapshot', 'restore'] as const);
export const BACKUP_ENCRYPTION_ALGORITHM = 'aes-256-gcm' as const;
export type BackupResource = typeof BACKUP_RESOURCE_TYPES[number];
export type ProviderBackupOperation = typeof BACKUP_PROVIDER_OPERATIONS[number];
export type BackupRole = 'user' | 'provider' | 'tenant_master' | 'monitor';
export type BackupDate = Date | string | number;
export interface BackupMetadataObject { readonly [key: string]: BackupMetadata; }
export type BackupMetadata = null | string | number | boolean | readonly BackupMetadata[] | BackupMetadataObject;
export interface BackupIdentity { readonly tenantId: string; readonly userId: string | null; readonly role: BackupRole }
export interface UserBackupScope { readonly schemaVersion: 1; readonly scopeType: 'user-self-service'; readonly tenantId: string; readonly userId: string; readonly resources: readonly BackupResource[]; readonly issuedAt: string; readonly expiresAt: string | null; readonly sessionBinding: 'request-only'; readonly sessionSecrets: false }
export interface ProviderBackupScope { readonly schemaVersion: 1; readonly scopeType: 'provider-encrypted-tenant'; readonly providerId: string; readonly tenantId: string; readonly userId: null; readonly resources: readonly BackupResource[]; readonly operations: readonly ProviderBackupOperation[]; readonly issuedAt: string; readonly expiresAt: string; readonly encryptedContentOnly: true; readonly plaintextAccess: false; readonly sessionAccess: false; readonly sessionSecrets: false; readonly encryptionKeyReference: string }
export type BackupScope = UserBackupScope | ProviderBackupScope;
export interface ArchiveEntry { readonly resource: BackupResource; readonly path: string; readonly bytes: number; readonly sha256: string; readonly mediaType?: string }
export interface BackupManifest { readonly schemaVersion: 1; readonly archiveId: string; readonly format: string; readonly tenantId: string; readonly userId: string | null; readonly resources: readonly BackupResource[]; readonly createdAt: string; readonly entries: readonly ArchiveEntry[]; readonly encryptedContent: true; readonly manifestSha256: string }
export interface EncryptedArchiveMetadata { readonly envelopeVersion: 1; readonly algorithm: 'aes-256-gcm'; readonly keyReference: string; readonly aad: string; readonly iv: string; readonly authTag: string; readonly ciphertext: string; readonly plaintextSha256: string }
export interface BackupLinkRecord { readonly schemaVersion: 1; readonly linkId: string; readonly archiveId: string; readonly tenantId: string; readonly userId: string | null; readonly resources: readonly BackupResource[]; readonly issuedAt: string; readonly expiresAt: string; readonly revokedAt: string | null; readonly tokenSha256: string; readonly href: string; readonly oneTime: false; readonly revokeReason?: string }
export interface RecoveryObjectives { readonly schemaVersion: 1; readonly objectiveType: 'tenant-disaster-recovery'; readonly rpoMinutes: number; readonly rtoMinutes: number; readonly retentionDays: number; readonly measuredFrom: 'last-successful-backup' | 'last-replicated-checkpoint' }
export interface RestorePlan { readonly schemaVersion: 1; readonly planType: 'restore'; readonly archiveId: string; readonly tenantId: string; readonly userId: string | null; readonly resources: readonly BackupResource[]; readonly overwrite: boolean; readonly integrityRequired: true; readonly privacyValidated: true; readonly plannedAt: string; readonly status: 'ready-for-integrity-check' | 'validated' }
type RecordValue = Record<string, unknown>;
type BackupContractError = Error & { code: string };
const resources = new Set<string>(BACKUP_RESOURCE_TYPES); const operations = new Set<string>(BACKUP_PROVIDER_OPERATIONS);
const idPattern = /^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,127}$/u; const refPattern = /^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$/u; const pathPattern = /^(?!\/)(?!.*(?:^|\/)(?:\.|\.\.)\/?)[A-Za-z0-9._@+()\-/]{1,512}$/u; const checksumPattern = /^[a-f0-9]{64}$/u; const linkIdPattern = /^[0-9a-f-]{36}$/u; const sensitivePattern = /^(?:session(?:id|token|secret)?|session[_-].*|access[_-]?token|refresh[_-]?token|cookie|authorization|password|passphrase|private[_-]?key|credential(?:s)?|secret)$/iu;
export function backupError(message: string, code = 'BACKUP_CONTRACT_ERROR'): BackupContractError { const error = new Error(`Backup contract error: ${message}`) as BackupContractError; error.code = code; return error; }
function plain(value: unknown): value is RecordValue { return value !== null && typeof value === 'object' && !Array.isArray(value) && (Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null); }
function object(value: unknown, name: string): asserts value is RecordValue { if (!plain(value)) throw backupError(`${name} must be an object`, 'INVALID_CONTRACT'); }
function id(value: unknown, name: string): string { if (typeof value !== 'string' || !idPattern.test(value)) throw backupError(`${name} is invalid`, 'INVALID_IDENTITY'); return value; }
function reference(value: unknown, name: string): string { if (typeof value !== 'string' || !refPattern.test(value)) throw backupError(`${name} is invalid`, 'INVALID_REFERENCE'); return value; }
function date(value: unknown, name: string): Date { const result = value instanceof Date ? new Date(value.getTime()) : new Date(value as string | number); if (Number.isNaN(result.getTime())) throw backupError(`${name} is invalid`, 'INVALID_TIMESTAMP'); return result; }
function integer(value: unknown, name: string, min: number, max: number): number { if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < min || value > max) throw backupError(`${name} must be an integer between ${min} and ${max}`, 'INVALID_NUMBER'); return value; }
function checksum(value: unknown, name = 'checksum'): string { if (typeof value !== 'string' || !checksumPattern.test(value)) throw backupError(`${name} must be a lowercase SHA-256 digest`, 'INVALID_CHECKSUM'); return value; }
function resourceList(value: unknown, name = 'resources'): readonly BackupResource[] { if (!Array.isArray(value) || value.length === 0) throw backupError(`${name} must be a non-empty array`, 'INVALID_RESOURCES'); const result = [...new Set(value)]; if (result.some((item) => typeof item !== 'string' || !resources.has(item))) throw backupError(`${name} contains an unsupported resource`, 'INVALID_RESOURCES'); return Object.freeze(result as BackupResource[]); }
export function assertNoSessionSecrets(value: unknown): void { safe(value); }
function safe(value: unknown, path = 'metadata'): void { if (Array.isArray(value)) { value.forEach((item, index) => safe(item, `${path}[${index}]`)); return; } if (plain(value)) { for (const [key, nested] of Object.entries(value)) { if (sensitivePattern.test(key)) throw backupError(`${path}.${key} is not allowed in backup metadata`, 'SESSION_SECRET_FORBIDDEN'); safe(nested, `${path}.${key}`); } return; } if (value !== null && !['string', 'number', 'boolean'].includes(typeof value)) throw backupError(`${path} contains an unsupported value`, 'INVALID_METADATA'); }
function canonical(value: unknown): BackupMetadata { if (value === null || ['string', 'number', 'boolean'].includes(typeof value)) return value as null | string | number | boolean; if (Array.isArray(value)) return value.map(canonical); if (plain(value)) return Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonical(value[key])])); throw backupError('value cannot be represented canonically', 'INVALID_METADATA'); }
export function canonicalJson(value: unknown): string { safe(value); return JSON.stringify(canonical(value)); }
export function sha256Hex(value: unknown): string { const input = Buffer.isBuffer(value) || value instanceof Uint8Array ? value : Buffer.from(typeof value === 'string' ? value : canonicalJson(value), 'utf8'); return createHash('sha256').update(input).digest('hex'); }
function identity(value: unknown, name = 'identity'): Readonly<BackupIdentity> { object(value, name); const role = value.role ?? 'user'; if (role !== 'user' && role !== 'provider' && role !== 'tenant_master' && role !== 'monitor') throw backupError(`${name}.role is invalid`, 'INVALID_IDENTITY'); return Object.freeze({ tenantId: id(value.tenantId, `${name}.tenantId`), userId: value.userId === null || value.userId === undefined ? null : id(value.userId, `${name}.userId`), role }); }

export interface UserScopeOptions { readonly session?: BackupIdentity | RecordValue | null; readonly targetUserId?: string; readonly resources?: readonly BackupResource[]; readonly issuedAt?: BackupDate; readonly expiresAt?: BackupDate | null }
export function createUserBackupScope({ session, targetUserId = plain(session) ? session.userId as string : undefined, resources: requested = BACKUP_RESOURCE_TYPES, issuedAt = new Date(), expiresAt = null }: UserScopeOptions = {}): Readonly<UserBackupScope> { const actor = identity(session, 'session'); if (actor.role !== 'user') throw backupError('user self-service requires a user session', 'USER_SCOPE_DENIED'); const target = id(targetUserId, 'targetUserId'); if (target !== actor.userId) throw backupError('a user backup can target only the authenticated user', 'USER_SCOPE_DENIED'); const issued = date(issuedAt, 'issuedAt'); const expiry = expiresAt === null ? null : date(expiresAt, 'expiresAt'); if (expiry !== null && expiry <= issued) throw backupError('expiresAt must be later than issuedAt', 'INVALID_TIMESTAMP'); const scope: UserBackupScope = { schemaVersion: 1, scopeType: 'user-self-service', tenantId: actor.tenantId, userId: actor.userId, resources: resourceList(requested), issuedAt: issued.toISOString(), expiresAt: expiry?.toISOString() ?? null, sessionBinding: 'request-only', sessionSecrets: false }; safe(scope); return Object.freeze(scope); }
function entry(value: unknown, index: number): Readonly<ArchiveEntry> { object(value, `entries[${index}]`); if (typeof value.resource !== 'string' || !resources.has(value.resource)) throw backupError(`entries[${index}].resource is unsupported`, 'INVALID_ARCHIVE'); if (typeof value.path !== 'string' || !pathPattern.test(value.path)) throw backupError(`entries[${index}].path is unsafe`, 'INVALID_ARCHIVE_PATH'); const result: { resource: BackupResource; path: string; bytes: number; sha256: string; mediaType?: string } = { resource: value.resource as BackupResource, path: value.path, bytes: integer(value.bytes, `entries[${index}].bytes`, 0, Number.MAX_SAFE_INTEGER), sha256: checksum(value.sha256, `entries[${index}].sha256`) }; if (value.mediaType !== undefined) { if (typeof value.mediaType !== 'string' || value.mediaType.length === 0 || value.mediaType.length > 255) throw backupError(`entries[${index}].mediaType is invalid`, 'INVALID_ARCHIVE'); result.mediaType = value.mediaType; } return Object.freeze(result); }
export function createArchiveManifest({ scope, archiveId = randomUUID(), entries, createdAt = new Date(), format = 'gulogulo-backup-tar' }: { readonly scope?: BackupScope | RecordValue; readonly archiveId?: string; readonly entries?: readonly ArchiveEntry[]; readonly createdAt?: BackupDate; readonly format?: string } = {}): Readonly<BackupManifest> { object(scope, 'scope'); const tenantId = id(scope.tenantId, 'scope.tenantId'); const userId = scope.userId === null ? null : id(scope.userId, 'scope.userId'); const scopeResources = resourceList(scope.resources, 'scope.resources'); id(archiveId, 'archiveId'); if (!Array.isArray(entries) || entries.length === 0) throw backupError('entries must be a non-empty array', 'INVALID_ARCHIVE'); const created = date(createdAt, 'createdAt'); if (typeof format !== 'string' || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/u.test(format)) throw backupError('format is invalid', 'INVALID_ARCHIVE'); const base = { schemaVersion: 1 as const, archiveId, format, tenantId, userId, resources: Object.freeze([...scopeResources]), createdAt: created.toISOString(), entries: Object.freeze(entries.map(entry)), encryptedContent: true as const }; safe(base); return Object.freeze({ ...base, manifestSha256: sha256Hex(base) }); }
export function verifyArchiveManifest(manifest: BackupManifest, contentByPath: Readonly<Record<string, string | Uint8Array>> = {}): Readonly<{ archiveId: string; manifestSha256: string; entries: readonly Readonly<{ path: string; status: 'not-present' | 'verified'; sha256?: string; bytes?: number }>[]; complete: boolean }> { object(manifest, 'manifest'); if (manifest.schemaVersion !== 1) throw backupError('manifest schemaVersion is unsupported', 'INVALID_ARCHIVE'); if (typeof manifest.manifestSha256 !== 'string') throw backupError('manifestSha256 is required', 'INVALID_ARCHIVE'); const { manifestSha256, ...base } = manifest; if (sha256Hex(base) !== manifestSha256) throw backupError('manifest digest does not match', 'INTEGRITY_FAILED'); const found: Readonly<{ path: string; status: 'not-present' | 'verified'; sha256?: string; bytes?: number }>[] = []; for (const member of manifest.entries) { const content = contentByPath[member.path]; if (content === undefined) { found.push(Object.freeze({ path: member.path, status: 'not-present' as const })); continue; } const actual = sha256Hex(content); if (actual !== member.sha256) throw backupError(`checksum mismatch for ${member.path}`, 'INTEGRITY_FAILED'); const bytes = Buffer.byteLength(content); if (bytes !== member.bytes) throw backupError(`size mismatch for ${member.path}`, 'INTEGRITY_FAILED'); found.push(Object.freeze({ path: member.path, status: 'verified' as const, sha256: actual, bytes })); } return Object.freeze({ archiveId: manifest.archiveId, manifestSha256, entries: Object.freeze(found), complete: found.every((member) => member.status === 'verified') }); }
function key(value: unknown): Buffer { if (!(Buffer.isBuffer(value) || value instanceof Uint8Array) || value.byteLength !== 32) throw backupError('encryption key must contain exactly 32 bytes', 'INVALID_ENCRYPTION_KEY'); return Buffer.from(value); }
export function encryptArchiveMetadata(metadata: Readonly<Record<string, BackupMetadata>>, { key: input, keyReference, aad = 'gulogulo-backup-metadata-v1', random = randomBytes }: { readonly key?: Uint8Array; readonly keyReference?: string; readonly aad?: string; readonly random?: (size: number) => Uint8Array } = {}): Readonly<EncryptedArchiveMetadata> { object(metadata, 'metadata'); safe(metadata); const encryptionKey = key(input); const reference = referenceKey(keyReference); if (typeof aad !== 'string' || aad.length === 0 || aad.length > 128) throw backupError('aad is invalid', 'INVALID_ENCRYPTION'); const iv = random(12); if (!(iv instanceof Uint8Array) || iv.byteLength !== 12) throw backupError('random source returned an invalid IV', 'INVALID_ENCRYPTION'); const cipher = createCipheriv(BACKUP_ENCRYPTION_ALGORITHM, encryptionKey, iv); cipher.setAAD(Buffer.from(aad)); const plaintext = Buffer.from(canonicalJson(metadata)); const ciphertext = Buffer.concat([cipher.update(plaintext), cipher.final()]); const envelope: EncryptedArchiveMetadata = { envelopeVersion: 1, algorithm: BACKUP_ENCRYPTION_ALGORITHM, keyReference: reference, aad, iv: Buffer.from(iv).toString('base64url'), authTag: cipher.getAuthTag().toString('base64url'), ciphertext: ciphertext.toString('base64url'), plaintextSha256: sha256Hex(plaintext) }; safe(envelope); return Object.freeze(envelope); }
function referenceKey(value: unknown): string { return reference(value, 'keyReference'); }
export function decryptArchiveMetadata(envelope: EncryptedArchiveMetadata, { key: input }: { readonly key?: Uint8Array } = {}): Readonly<Record<string, BackupMetadata>> { object(envelope, 'envelope'); if (envelope.envelopeVersion !== 1 || envelope.algorithm !== BACKUP_ENCRYPTION_ALGORITHM) throw backupError('unsupported archive envelope', 'INVALID_ENCRYPTION'); const encryptionKey = key(input); referenceKey(envelope.keyReference); if (typeof envelope.aad !== 'string' || typeof envelope.iv !== 'string' || typeof envelope.authTag !== 'string' || typeof envelope.ciphertext !== 'string') throw backupError('archive envelope is incomplete', 'INVALID_ENCRYPTION'); let plaintext: Buffer; try { const decipher = createDecipheriv(BACKUP_ENCRYPTION_ALGORITHM, encryptionKey, Buffer.from(envelope.iv, 'base64url')); decipher.setAAD(Buffer.from(envelope.aad)); decipher.setAuthTag(Buffer.from(envelope.authTag, 'base64url')); plaintext = Buffer.concat([decipher.update(Buffer.from(envelope.ciphertext, 'base64url')), decipher.final()]); } catch { throw backupError('archive metadata authentication failed', 'INTEGRITY_FAILED'); } if (sha256Hex(plaintext) !== envelope.plaintextSha256) throw backupError('archive metadata checksum mismatch', 'INTEGRITY_FAILED'); let result: unknown; try { result = JSON.parse(plaintext.toString()) as unknown; } catch { throw backupError('archive metadata is not valid JSON', 'INVALID_ENCRYPTION'); } object(result, 'metadata'); safe(result); return Object.freeze(result as Record<string, BackupMetadata>); }
export function createBackupLink({ archiveId, scope, baseUrl = 'https://download.invalid', issuedAt = new Date(), expiresAt = null, ttlMs = 900_000, token = randomBytes(32).toString('base64url') }: { readonly archiveId?: string; readonly scope?: BackupScope | RecordValue; readonly baseUrl?: string; readonly issuedAt?: BackupDate; readonly expiresAt?: BackupDate | null; readonly ttlMs?: number; readonly token?: string } = {}): Readonly<{ record: Readonly<BackupLinkRecord>; token: string }> { id(archiveId, 'archiveId'); object(scope, 'scope'); const tenantId = id(scope.tenantId, 'scope.tenantId'); const userId = scope.userId === null ? null : id(scope.userId, 'scope.userId'); const scopeResources = resourceList(scope.resources, 'scope.resources'); const issued = date(issuedAt, 'issuedAt'); const expires = expiresAt === null ? new Date(issued.getTime() + integer(ttlMs, 'ttlMs', 1_000, BACKUP_LINK_TTL_MAX_MS)) : date(expiresAt, 'expiresAt'); if (expires <= issued || expires.getTime() - issued.getTime() > BACKUP_LINK_TTL_MAX_MS) throw backupError('backup link expiry is outside the allowed window', 'INVALID_LINK'); if (typeof token !== 'string' || token.length < 32 || token.length > 512) throw backupError('token is invalid', 'INVALID_LINK'); let url: URL; try { url = new URL(baseUrl); } catch { throw backupError('baseUrl is invalid', 'INVALID_LINK'); } if (url.protocol !== 'https:' || url.username || url.password || url.search || url.hash) throw backupError('backup links require an HTTPS base URL without credentials', 'INVALID_LINK'); const linkId = randomUUID(); url.pathname = `${url.pathname.replace(/\/$/u, '')}/backup/${linkId}`; url.searchParams.set('token', token); const record: BackupLinkRecord = { schemaVersion: 1, linkId, archiveId: archiveId as string, tenantId, userId, resources: scopeResources, issuedAt: issued.toISOString(), expiresAt: expires.toISOString(), revokedAt: null, tokenSha256: sha256Hex(token), href: url.toString(), oneTime: false }; safe(record); return Object.freeze({ record: Object.freeze(record), token }); }
export function revokeBackupLink(link: BackupLinkRecord, { revokedAt = new Date(), reason = 'operator-revoked' }: { readonly revokedAt?: BackupDate; readonly reason?: string } = {}): Readonly<BackupLinkRecord> { object(link, 'link'); if (typeof link.linkId !== 'string' || !linkIdPattern.test(link.linkId)) throw backupError('linkId is invalid', 'INVALID_LINK'); if (typeof reason !== 'string' || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/u.test(reason)) throw backupError('reason is invalid', 'INVALID_LINK'); return Object.freeze({ ...link, revokedAt: date(revokedAt, 'revokedAt').toISOString(), revokeReason: reason }); }
export function assertBackupLinkUsable(link: BackupLinkRecord, { token, now = new Date() }: { readonly token?: string; readonly now?: BackupDate } = {}): true { object(link, 'link'); if (link.revokedAt !== null) throw backupError('backup link has been revoked', 'LINK_REVOKED'); if (date(now, 'now') >= date(link.expiresAt, 'link.expiresAt')) throw backupError('backup link has expired', 'LINK_EXPIRED'); if (typeof token !== 'string') throw backupError('link token is required', 'LINK_TOKEN_INVALID'); const expected = Buffer.from(checksum(link.tokenSha256, 'link.tokenSha256'), 'hex'); const actual = Buffer.from(sha256Hex(token), 'hex'); if (expected.length !== actual.length || !timingSafeEqual(expected, actual)) throw backupError('link token is invalid', 'LINK_TOKEN_INVALID'); return true; }
export function createProviderBackupScope({ providerId, tenantId, resources: requested = BACKUP_RESOURCE_TYPES, operations: requestedOperations = BACKUP_PROVIDER_OPERATIONS, encryptionKeyReference, issuedAt = new Date(), expiresAt }: { readonly providerId?: string; readonly tenantId?: string; readonly resources?: readonly BackupResource[]; readonly operations?: readonly ProviderBackupOperation[]; readonly encryptionKeyReference?: string; readonly issuedAt?: BackupDate; readonly expiresAt?: BackupDate } = {}): Readonly<ProviderBackupScope> { const provider = id(providerId, 'providerId'); const tenant = id(tenantId, 'tenantId'); const scopeResources = resourceList(requested); if (!Array.isArray(requestedOperations) || requestedOperations.length === 0 || requestedOperations.some((operation) => !operations.has(operation))) throw backupError('operations are invalid', 'INVALID_PROVIDER_SCOPE'); const issued = date(issuedAt, 'issuedAt'); const expires = date(expiresAt, 'expiresAt'); if (expires <= issued) throw backupError('expiresAt must be later than issuedAt', 'INVALID_TIMESTAMP'); const scope: ProviderBackupScope = { schemaVersion: 1, scopeType: 'provider-encrypted-tenant', providerId: provider, tenantId: tenant, userId: null, resources: scopeResources, operations: Object.freeze([...new Set(requestedOperations)]), issuedAt: issued.toISOString(), expiresAt: expires.toISOString(), encryptedContentOnly: true, plaintextAccess: false, sessionAccess: false, sessionSecrets: false, encryptionKeyReference: referenceKey(encryptionKeyReference) }; safe(scope); return Object.freeze(scope); }
function target(scope: BackupScope, value: BackupIdentity | RecordValue): Readonly<BackupIdentity> { const actor = identity(value, 'target'); if (scope.tenantId !== actor.tenantId) throw backupError('restore target crosses tenant boundary', 'TENANT_SCOPE_DENIED'); if (scope.scopeType === 'user-self-service' && scope.userId !== actor.userId) throw backupError('restore target crosses user boundary', 'USER_SCOPE_DENIED'); if (scope.scopeType === 'provider-encrypted-tenant' && actor.role !== 'provider') throw backupError('provider scope requires a provider restore actor', 'PROVIDER_SCOPE_DENIED'); return actor; }
export function createRestorePlan({ manifest, scope, target: actor, requestedResources = scope?.resources, overwrite = false, plannedAt = new Date() }: { readonly manifest?: BackupManifest; readonly scope?: BackupScope; readonly target?: BackupIdentity | RecordValue; readonly requestedResources?: readonly BackupResource[]; readonly overwrite?: boolean; readonly plannedAt?: BackupDate } = {}): Readonly<RestorePlan> { if (manifest === undefined || scope === undefined || actor === undefined) throw backupError('manifest, scope, and target are required', 'INVALID_CONTRACT'); target(scope, actor); if (manifest.tenantId !== scope.tenantId || manifest.userId !== scope.userId) throw backupError('manifest scope does not match restore scope', 'SCOPE_MISMATCH'); const selected = resourceList(requestedResources, 'requestedResources'); if (selected.some((item) => !scope.resources.includes(item))) throw backupError('restore requests a resource outside the authorized scope', 'RESOURCE_SCOPE_DENIED'); if (typeof overwrite !== 'boolean') throw backupError('overwrite must be boolean', 'INVALID_RESTORE_PLAN'); const plan: RestorePlan = { schemaVersion: 1, planType: 'restore', archiveId: manifest.archiveId, tenantId: scope.tenantId, userId: scope.userId, resources: selected, overwrite, integrityRequired: true, privacyValidated: true, plannedAt: date(plannedAt, 'plannedAt').toISOString(), status: 'ready-for-integrity-check' }; safe(plan); return Object.freeze(plan); }
export function validateRestorePlan(plan: RestorePlan, { manifest, scope, target: actor, contentByPath = {} }: { readonly manifest?: BackupManifest; readonly scope?: BackupScope; readonly target?: BackupIdentity | RecordValue; readonly contentByPath?: Readonly<Record<string, string | Uint8Array>> } = {}): Readonly<RestorePlan & { readonly integrity: ReturnType<typeof verifyArchiveManifest>; readonly validatedAt: string }> { if (manifest === undefined || scope === undefined || actor === undefined) throw backupError('manifest, scope, and target are required', 'INVALID_CONTRACT'); const restoreActor = target(scope, actor); if (plan.archiveId !== manifest.archiveId || plan.tenantId !== scope.tenantId || plan.userId !== scope.userId) throw backupError('restore plan identity does not match its archive scope', 'SCOPE_MISMATCH'); if (restoreActor.role === 'user' && plan.overwrite) throw backupError('user restores cannot overwrite existing data', 'RESTORE_POLICY_DENIED'); const integrity = verifyArchiveManifest(manifest, contentByPath); if (!integrity.complete) throw backupError('all archive members must be present before restore', 'INTEGRITY_INCOMPLETE'); return Object.freeze({ ...plan, status: 'validated' as const, integrity, privacyValidated: true as const, validatedAt: new Date().toISOString() }); }
export function createRecoveryObjectives({ rpoMinutes = 15, rtoMinutes = 60, retentionDays = 28, measuredFrom = 'last-successful-backup' }: { readonly rpoMinutes?: number; readonly rtoMinutes?: number; readonly retentionDays?: number; readonly measuredFrom?: RecoveryObjectives['measuredFrom'] } = {}): Readonly<RecoveryObjectives> { integer(rpoMinutes, 'rpoMinutes', 1, 525_600); integer(rtoMinutes, 'rtoMinutes', 1, 525_600); if (rtoMinutes < rpoMinutes) throw backupError('rtoMinutes cannot be lower than rpoMinutes', 'INVALID_RECOVERY_OBJECTIVES'); integer(retentionDays, 'retentionDays', 28, 36_500); if (measuredFrom !== 'last-successful-backup' && measuredFrom !== 'last-replicated-checkpoint') throw backupError('measuredFrom is invalid', 'INVALID_RECOVERY_OBJECTIVES'); return Object.freeze({ schemaVersion: 1, objectiveType: 'tenant-disaster-recovery', rpoMinutes, rtoMinutes, retentionDays, measuredFrom }); }
export function createDrRehearsalRecord({ rehearsalId = randomUUID(), tenantId, archiveId, objectives, startedAt, endedAt, outcome, observedRpoMinutes, observedRtoMinutes, integrityVerified, privacyVerified, evidenceSha256, runbookVersion = '1' }: { readonly rehearsalId?: string; readonly tenantId?: string; readonly archiveId?: string; readonly objectives?: RecoveryObjectives; readonly startedAt?: BackupDate; readonly endedAt?: BackupDate; readonly outcome?: 'passed' | 'failed' | 'inconclusive'; readonly observedRpoMinutes?: number; readonly observedRtoMinutes?: number; readonly integrityVerified?: boolean; readonly privacyVerified?: boolean; readonly evidenceSha256?: string; readonly runbookVersion?: string } = {}): Readonly<Record<string, unknown>> { id(rehearsalId, 'rehearsalId'); id(tenantId, 'tenantId'); id(archiveId, 'archiveId'); object(objectives, 'objectives'); const rpo = integer(objectives.rpoMinutes, 'objectives.rpoMinutes', 1, 525_600); const rto = integer(objectives.rtoMinutes, 'objectives.rtoMinutes', 1, 525_600); if (rto < rpo) throw backupError('objectives.rtoMinutes cannot be lower than objectives.rpoMinutes', 'INVALID_REHEARSAL'); const started = date(startedAt, 'startedAt'); const ended = date(endedAt, 'endedAt'); if (ended < started) throw backupError('endedAt must not precede startedAt', 'INVALID_REHEARSAL'); if (outcome !== 'passed' && outcome !== 'failed' && outcome !== 'inconclusive') throw backupError('outcome is invalid', 'INVALID_REHEARSAL'); const observedRpo = integer(observedRpoMinutes, 'observedRpoMinutes', 0, 525_600); const observedRto = integer(observedRtoMinutes, 'observedRtoMinutes', 0, 525_600); if (typeof integrityVerified !== 'boolean' || typeof privacyVerified !== 'boolean') throw backupError('integrityVerified and privacyVerified must be boolean', 'INVALID_REHEARSAL'); if (evidenceSha256 !== undefined) checksum(evidenceSha256, 'evidenceSha256'); if (typeof runbookVersion !== 'string' || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,31}$/u.test(runbookVersion)) throw backupError('runbookVersion is invalid', 'INVALID_REHEARSAL'); if (outcome === 'passed' && (!integrityVerified || !privacyVerified || observedRpo > rpo || observedRto > rto)) throw backupError('a passed rehearsal must satisfy integrity, privacy, RPO, and RTO objectives', 'INVALID_REHEARSAL'); const record = { schemaVersion: 1, rehearsalId, tenantId: tenantId as string, archiveId: archiveId as string, startedAt: started.toISOString(), endedAt: ended.toISOString(), durationMinutes: Math.ceil((ended.getTime() - started.getTime()) / 60_000), outcome, observedRpoMinutes: observedRpo, observedRtoMinutes: observedRto, integrityVerified, privacyVerified, evidenceSha256: evidenceSha256 ?? null, runbookVersion }; safe(record); return Object.freeze(record); }
